/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejq11;

import java.awt.Color;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ciber
 */
public class JFAddOrders extends javax.swing.JFrame {

    /**
     * Creates new form JFAddOrders
     */
    private ListaPedidos listaP;

    public JFAddOrders(ListaPedidos listaP) {
        initComponents();
        this.listaP = listaP;
        showHidePanelExtras(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupNombre = new javax.swing.ButtonGroup();
        btnGroupExtra1 = new javax.swing.ButtonGroup();
        btnGroupExtra2 = new javax.swing.ButtonGroup();
        btnGroupExtra3 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelCliente = new javax.swing.JPanel();
        lblNombreCliente = new javax.swing.JLabel();
        lblApellidosCliente = new javax.swing.JLabel();
        lblDniCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidosCliente = new javax.swing.JTextField();
        MaskFormatter maskDNI = null;

        try {
            maskDNI = new MaskFormatter("########U");
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        formatTxtDni = new javax.swing.JFormattedTextField(maskDNI);
        lblErrorNombre = new javax.swing.JLabel();
        lblErrorApellido = new javax.swing.JLabel();
        lblErrorDni = new javax.swing.JLabel();
        lblDatosCliente = new javax.swing.JLabel();
        jPanelValidar = new javax.swing.JPanel();
        btnValidar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnVolber = new javax.swing.JButton();
        jPanelPizza = new javax.swing.JPanel();
        lblNombrePedido = new javax.swing.JLabel();
        radioBtnNombreProducto1 = new javax.swing.JRadioButton();
        radioBtnNombreProducto2 = new javax.swing.JRadioButton();
        radioBtnNombreProducto3 = new javax.swing.JRadioButton();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        checkBoxExtras = new javax.swing.JCheckBox();
        jPanelExtras = new javax.swing.JPanel();
        lblExtra1 = new javax.swing.JLabel();
        radioBtnExtra1_1 = new javax.swing.JRadioButton();
        radioBtnExtra1_2 = new javax.swing.JRadioButton();
        radioBtnExtra1_3 = new javax.swing.JRadioButton();
        radioBtnExtra1_4 = new javax.swing.JRadioButton();
        radioBtnExtra1_5 = new javax.swing.JRadioButton();
        lblExtra2 = new javax.swing.JLabel();
        radioBtnExtra2_1 = new javax.swing.JRadioButton();
        radioBtnExtra2_2 = new javax.swing.JRadioButton();
        radioBtnExtra2_3 = new javax.swing.JRadioButton();
        radioBtnExtra2_4 = new javax.swing.JRadioButton();
        radioBtnExtra2_5 = new javax.swing.JRadioButton();
        lblExtra3 = new javax.swing.JLabel();
        radioBtnExtra3_1 = new javax.swing.JRadioButton();
        radioBtnExtra3_2 = new javax.swing.JRadioButton();
        radioBtnExtra3_3 = new javax.swing.JRadioButton();
        radioBtnExtra3_4 = new javax.swing.JRadioButton();
        radioBtnExtra3_5 = new javax.swing.JRadioButton();
        lblErrorCantidad = new javax.swing.JLabel();
        lblErrorExtra = new javax.swing.JLabel();
        lblErrorNombrePizza = new javax.swing.JLabel();
        lblNavegacion = new javax.swing.JLabel();
        lblPizza = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNombreCliente.setText("Nombre:");

        lblApellidosCliente.setText("Apellidos:");

        lblDniCliente.setText("DNI:");

        txtNombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreClienteKeyTyped(evt);
            }
        });

        txtApellidosCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosClienteKeyTyped(evt);
            }
        });

        formatTxtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formatTxtDniKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCliente)
                    .addComponent(lblApellidosCliente)
                    .addComponent(lblDniCliente))
                .addGap(51, 51, 51)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(txtApellidosCliente)
                    .addComponent(formatTxtDni)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorNombre)
                            .addComponent(lblErrorApellido)
                            .addComponent(lblErrorDni))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addGap(21, 43, Short.MAX_VALUE)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApellidosCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClienteLayout.createSequentialGroup()
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(txtApellidosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDniCliente)
                    .addComponent(formatTxtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorDni, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblDatosCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDatosCliente.setText("Datos del Cliente");

        jPanelValidar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnVolber.setText("Volver");
        btnVolber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelValidarLayout = new javax.swing.GroupLayout(jPanelValidar);
        jPanelValidar.setLayout(jPanelValidarLayout);
        jPanelValidarLayout.setHorizontalGroup(
            jPanelValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelValidarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnValidar)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnVolber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelValidarLayout.setVerticalGroup(
            jPanelValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelValidarLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanelValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValidar)
                    .addComponent(btnGuardar)
                    .addComponent(btnVolber))
                .addGap(32, 32, 32))
        );

        jPanelPizza.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNombrePedido.setText("Nombre:");

        btnGroupNombre.add(radioBtnNombreProducto1);
        radioBtnNombreProducto1.setText("Provenzal");

        btnGroupNombre.add(radioBtnNombreProducto2);
        radioBtnNombreProducto2.setSelected(true);
        radioBtnNombreProducto2.setText("Barbacoa");

        btnGroupNombre.add(radioBtnNombreProducto3);
        radioBtnNombreProducto3.setText("Mediterránea");

        lblCantidad.setText("Cantidad");

        txtCantidad.setText("1");
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        checkBoxExtras.setText("Extras");
        checkBoxExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxExtrasActionPerformed(evt);
            }
        });

        jPanelExtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblExtra1.setText("Ingrediente Extra 1:");

        btnGroupExtra1.add(radioBtnExtra1_1);
        radioBtnExtra1_1.setText("1");

        btnGroupExtra1.add(radioBtnExtra1_2);
        radioBtnExtra1_2.setText("2");

        btnGroupExtra1.add(radioBtnExtra1_3);
        radioBtnExtra1_3.setText("3");

        btnGroupExtra1.add(radioBtnExtra1_4);
        radioBtnExtra1_4.setText("4");

        btnGroupExtra1.add(radioBtnExtra1_5);
        radioBtnExtra1_5.setText("5");

        lblExtra2.setText("Ingrediente Extra 2:");

        btnGroupExtra2.add(radioBtnExtra2_1);
        radioBtnExtra2_1.setText("1");

        btnGroupExtra2.add(radioBtnExtra2_2);
        radioBtnExtra2_2.setText("2");

        btnGroupExtra2.add(radioBtnExtra2_3);
        radioBtnExtra2_3.setText("3");

        btnGroupExtra2.add(radioBtnExtra2_4);
        radioBtnExtra2_4.setText("4");

        btnGroupExtra2.add(radioBtnExtra2_5);
        radioBtnExtra2_5.setText("5");

        lblExtra3.setText("Ingrediente Extra 3:");

        btnGroupExtra3.add(radioBtnExtra3_1);
        radioBtnExtra3_1.setText("1");

        btnGroupExtra3.add(radioBtnExtra3_2);
        radioBtnExtra3_2.setText("2");

        btnGroupExtra3.add(radioBtnExtra3_3);
        radioBtnExtra3_3.setText("3");

        btnGroupExtra3.add(radioBtnExtra3_4);
        radioBtnExtra3_4.setText("4");

        btnGroupExtra3.add(radioBtnExtra3_5);
        radioBtnExtra3_5.setText("5");

        javax.swing.GroupLayout jPanelExtrasLayout = new javax.swing.GroupLayout(jPanelExtras);
        jPanelExtras.setLayout(jPanelExtrasLayout);
        jPanelExtrasLayout.setHorizontalGroup(
            jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelExtrasLayout.createSequentialGroup()
                        .addComponent(lblExtra1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioBtnExtra1_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBtnExtra1_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBtnExtra1_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBtnExtra1_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBtnExtra1_5))
                    .addGroup(jPanelExtrasLayout.createSequentialGroup()
                        .addComponent(lblExtra2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioBtnExtra2_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBtnExtra2_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBtnExtra2_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBtnExtra2_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBtnExtra2_5))
                    .addGroup(jPanelExtrasLayout.createSequentialGroup()
                        .addComponent(lblExtra3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioBtnExtra3_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBtnExtra3_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBtnExtra3_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBtnExtra3_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBtnExtra3_5)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanelExtrasLayout.setVerticalGroup(
            jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExtra1)
                    .addComponent(radioBtnExtra1_1)
                    .addComponent(radioBtnExtra1_2)
                    .addComponent(radioBtnExtra1_3)
                    .addComponent(radioBtnExtra1_4)
                    .addComponent(radioBtnExtra1_5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExtra2)
                    .addComponent(radioBtnExtra2_1)
                    .addComponent(radioBtnExtra2_2)
                    .addComponent(radioBtnExtra2_3)
                    .addComponent(radioBtnExtra2_4)
                    .addComponent(radioBtnExtra2_5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExtra3)
                    .addComponent(radioBtnExtra3_1)
                    .addComponent(radioBtnExtra3_2)
                    .addComponent(radioBtnExtra3_3)
                    .addComponent(radioBtnExtra3_4)
                    .addComponent(radioBtnExtra3_5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPizzaLayout = new javax.swing.GroupLayout(jPanelPizza);
        jPanelPizza.setLayout(jPanelPizzaLayout);
        jPanelPizzaLayout.setHorizontalGroup(
            jPanelPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPizzaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorExtra)
                    .addComponent(checkBoxExtras)
                    .addGroup(jPanelPizzaLayout.createSequentialGroup()
                        .addGroup(jPanelPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombrePedido)
                            .addComponent(lblCantidad))
                        .addGap(51, 51, 51)
                        .addGroup(jPanelPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPizzaLayout.createSequentialGroup()
                                .addComponent(radioBtnNombreProducto1)
                                .addGap(18, 18, 18)
                                .addComponent(radioBtnNombreProducto2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrorNombrePizza)
                                    .addComponent(radioBtnNombreProducto3)))
                            .addGroup(jPanelPizzaLayout.createSequentialGroup()
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanelExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPizzaLayout.setVerticalGroup(
            jPanelPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPizzaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePedido)
                    .addComponent(radioBtnNombreProducto1)
                    .addComponent(radioBtnNombreProducto2)
                    .addComponent(radioBtnNombreProducto3))
                .addGroup(jPanelPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPizzaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidad)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPizzaLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblErrorNombrePizza)))
                .addGap(18, 18, 18)
                .addComponent(checkBoxExtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorExtra)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lblNavegacion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNavegacion.setText("Validación");

        lblPizza.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPizza.setText("Pizza");

        jLayeredPane1.setLayer(jPanelCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblDatosCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelValidar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelPizza, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblNavegacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblPizza, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPizza)
                            .addComponent(jPanelPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDatosCliente)
                            .addComponent(jPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(lblNavegacion)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelValidar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblDatosCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPizza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblNavegacion)
                .addGap(18, 18, 18)
                .addComponent(jPanelValidar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolberActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolberActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        boolean ok = true;

        if (this.txtNombreCliente.getText().isEmpty()) {
            this.lblErrorNombre.setForeground(Color.red);
            this.lblErrorNombre.setText("El nombre no puede estar vacio");
            ok = false;
        } else {
            ok = true;
            this.lblErrorNombre.setText("");
        }
        if (this.txtApellidosCliente.getText().isEmpty()) {
            this.lblErrorApellido.setForeground(Color.red);
            this.lblErrorApellido.setText("El apellido no puede estar vacio");
            ok = false;
        } else {
            ok = true;
            this.lblErrorApellido.setText("");
        }
        try {
            if (Utilidades.checkDni(this.formatTxtDni.getText())) {
                this.lblErrorDni.setText("");
                ok = true;
            }
        } catch (ExcepcionPropia e) {
            this.lblErrorDni.setForeground(Color.red);
            this.lblErrorDni.setText(e.getMessage());
            ok = false;
        } catch (NumberFormatException e) {
            this.lblErrorDni.setForeground(Color.red);
            this.lblErrorDni.setText("El DNI no puede estar vacio");
            ok = false;
        }
        try {
            if (Utilidades.checkRango(Integer.parseInt(this.txtCantidad.getText()))) {
                this.lblErrorCantidad.setText("");
                ok = true;
            }
        } catch (NumberFormatException e) {
            this.lblErrorCantidad.setForeground(Color.red);
            this.lblErrorCantidad.setText("ERROR: La cantidad tiene que ser numerica");
            ok = false;
        } catch (ExcepcionPropia e) {
            this.lblErrorCantidad.setForeground(Color.red);
            this.lblErrorCantidad.setText(e.getMessage());
            ok = false;
        }
        ok = isRadioBtnExtraSelected();
        if (!ok) {
            this.lblErrorExtra.setForeground(Color.red);
            this.lblErrorExtra.setText("ERROR: Si elije un extra, debe seleccionar al menos un ingrediente.");
        } else {
            this.lblErrorExtra.setText("");
        }
        if (ok) {
            this.btnGuardar.setEnabled(true);
        } else {
            this.btnGuardar.setEnabled(false);
        }

    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombre, apell, dni, nomPizza;
        int cantidad, extra1 = 0, extra2 = 0, extra3 = 0;
        boolean extra, insertado;
        Pedido pedido;

        nombre = this.txtNombreCliente.getText();
        apell = this.txtApellidosCliente.getText();
        dni = this.formatTxtDni.getText();
        nomPizza = getSelectedButtonText(this.btnGroupNombre);
        cantidad = Integer.parseInt(this.txtCantidad.getText());
        extra = this.checkBoxExtras.isSelected();
        if (extra) {
            if (this.btnGroupExtra1.isSelected(btnGroupExtra1.getSelection())) {
                if (getSelectedButtonText(this.btnGroupExtra1) != null) {
                    extra1 = Integer.parseInt(getSelectedButtonText(this.btnGroupExtra1));
                }
            }
            if (this.btnGroupExtra2.isSelected(btnGroupExtra2.getSelection())) {
                if (getSelectedButtonText(this.btnGroupExtra2) != null) {
                    extra2 = Integer.parseInt(getSelectedButtonText(this.btnGroupExtra2));
                }
            }
            if (this.btnGroupExtra3.isSelected(btnGroupExtra3.getSelection())) {
                if (getSelectedButtonText(this.btnGroupExtra3) != null) {
                    extra3 = Integer.parseInt(getSelectedButtonText(this.btnGroupExtra3));
                }
            }
        }

        if (extra) {
            pedido = new Pedido(nombre, apell, dni, nomPizza, cantidad, extra, extra1, extra2, extra3);
        } else {
            pedido = new Pedido(nombre, apell, dni, nomPizza, cantidad, extra);
        }
        insertado = listaP.addPedido(pedido);
        if (insertado) {
            JOptionPane.showMessageDialog(this, "Pedido insertado");
        } else {
            JOptionPane.showMessageDialog(this, "No se ha podido insertar el pedido");
        }
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreClienteKeyTyped
        this.btnGuardar.setEnabled(false);
    }//GEN-LAST:event_txtNombreClienteKeyTyped

    private void txtApellidosClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosClienteKeyTyped
        this.btnGuardar.setEnabled(false);
    }//GEN-LAST:event_txtApellidosClienteKeyTyped

    private void formatTxtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formatTxtDniKeyTyped
        this.btnGuardar.setEnabled(false);
    }//GEN-LAST:event_formatTxtDniKeyTyped

    private void checkBoxExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxExtrasActionPerformed
        boolean ok;
        if (checkBoxExtras.isSelected()) {
            showHidePanelExtras(true);
            ok = isRadioBtnExtraSelected();
            if (!ok) {
                this.btnGuardar.setEnabled(false);
            }
        } else {
            showHidePanelExtras(false);
        }
    }//GEN-LAST:event_checkBoxExtrasActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        this.btnGuardar.setEnabled(false);
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void showHidePanelExtras(boolean visible) {
        this.jPanelExtras.setVisible(visible);
    }

    private boolean isRadioBtnExtraSelected() {
        boolean ok = true;

        if (this.checkBoxExtras.isSelected()) {
            if (!this.radioBtnExtra1_1.isSelected() && !this.radioBtnExtra1_2.isSelected() && !this.radioBtnExtra1_3.isSelected() && !this.radioBtnExtra1_4.isSelected() && !this.radioBtnExtra1_5.isSelected()) {
                if (!this.radioBtnExtra2_1.isSelected() && !this.radioBtnExtra2_2.isSelected() && !this.radioBtnExtra2_3.isSelected() && !this.radioBtnExtra2_4.isSelected() && !this.radioBtnExtra2_5.isSelected()) {
                    if (!this.radioBtnExtra3_1.isSelected() && !this.radioBtnExtra3_2.isSelected() && !this.radioBtnExtra3_3.isSelected() && !this.radioBtnExtra3_4.isSelected() && !this.radioBtnExtra3_5.isSelected()) {
                        ok = false;
                    } else {
                        this.lblErrorExtra.setText("");
                    }
                } else {
                    this.lblErrorExtra.setText("");
                }
            } else {
                this.lblErrorExtra.setText("");
            }
        }

        return ok;
    }

    private String getSelectedButtonText(javax.swing.ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupExtra1;
    private javax.swing.ButtonGroup btnGroupExtra2;
    private javax.swing.ButtonGroup btnGroupExtra3;
    private javax.swing.ButtonGroup btnGroupNombre;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnValidar;
    private javax.swing.JButton btnVolber;
    private javax.swing.JCheckBox checkBoxExtras;
    private javax.swing.JFormattedTextField formatTxtDni;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelExtras;
    private javax.swing.JPanel jPanelPizza;
    private javax.swing.JPanel jPanelValidar;
    private javax.swing.JLabel lblApellidosCliente;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDatosCliente;
    private javax.swing.JLabel lblDniCliente;
    private javax.swing.JLabel lblErrorApellido;
    private javax.swing.JLabel lblErrorCantidad;
    private javax.swing.JLabel lblErrorDni;
    private javax.swing.JLabel lblErrorExtra;
    private javax.swing.JLabel lblErrorNombre;
    private javax.swing.JLabel lblErrorNombrePizza;
    private javax.swing.JLabel lblExtra1;
    private javax.swing.JLabel lblExtra2;
    private javax.swing.JLabel lblExtra3;
    private javax.swing.JLabel lblNavegacion;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombrePedido;
    private javax.swing.JLabel lblPizza;
    private javax.swing.JRadioButton radioBtnExtra1_1;
    private javax.swing.JRadioButton radioBtnExtra1_2;
    private javax.swing.JRadioButton radioBtnExtra1_3;
    private javax.swing.JRadioButton radioBtnExtra1_4;
    private javax.swing.JRadioButton radioBtnExtra1_5;
    private javax.swing.JRadioButton radioBtnExtra2_1;
    private javax.swing.JRadioButton radioBtnExtra2_2;
    private javax.swing.JRadioButton radioBtnExtra2_3;
    private javax.swing.JRadioButton radioBtnExtra2_4;
    private javax.swing.JRadioButton radioBtnExtra2_5;
    private javax.swing.JRadioButton radioBtnExtra3_1;
    private javax.swing.JRadioButton radioBtnExtra3_2;
    private javax.swing.JRadioButton radioBtnExtra3_3;
    private javax.swing.JRadioButton radioBtnExtra3_4;
    private javax.swing.JRadioButton radioBtnExtra3_5;
    private javax.swing.JRadioButton radioBtnNombreProducto1;
    private javax.swing.JRadioButton radioBtnNombreProducto2;
    private javax.swing.JRadioButton radioBtnNombreProducto3;
    private javax.swing.JTextField txtApellidosCliente;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
}
